{"timestamp":"2025-06-01T20:46:40.952794","level":"info","event":"DAG bundles loaded: dags-folder","logger":"airflow.dag_processing.bundles.manager.DagBundlesManager"}
{"timestamp":"2025-06-01T20:46:40.953368","level":"info","event":"Filling up the DagBag from /home/ubuntu/airflow/dags/long_term_strategy_dag.py","logger":"airflow.models.dagbag.DagBag"}
{"timestamp":"2025-06-01T20:46:41.581954","level":"info","event":"Found credentials in environment variables.","logger":"botocore.credentials"}
{"timestamp":"2025-06-01T20:46:41.904358","level":"error","event":"Task failed with exception","logger":"task","error_detail":[{"exc_type":"S3UploadFailedError","exc_value":"Failed to upload /home/ubuntu/data/longterm_signal_history.parquet to ai-buffett-backups/longterm/longterm_signal_history.parquet: An error occurred (InvalidAccessKeyId) when calling the PutObject operation: The AWS Access Key Id you provided does not exist in our records.","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/ubuntu/airflow_venv/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":838,"name":"run"},{"filename":"/home/ubuntu/airflow_venv/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":1130,"name":"_execute_task"},{"filename":"/home/ubuntu/airflow_venv/lib/python3.12/site-packages/airflow/sdk/bases/operator.py","lineno":408,"name":"wrapper"},{"filename":"/home/ubuntu/airflow_venv/lib/python3.12/site-packages/airflow/sdk/bases/decorator.py","lineno":251,"name":"execute"},{"filename":"/home/ubuntu/airflow_venv/lib/python3.12/site-packages/airflow/sdk/bases/operator.py","lineno":408,"name":"wrapper"},{"filename":"/home/ubuntu/airflow_venv/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":216,"name":"execute"},{"filename":"/home/ubuntu/airflow_venv/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":239,"name":"execute_callable"},{"filename":"/home/ubuntu/airflow_venv/lib/python3.12/site-packages/airflow/sdk/execution_time/callback_runner.py","lineno":81,"name":"run"},{"filename":"/home/ubuntu/airflow/dags/long_term_strategy_dag.py","lineno":79,"name":"backup_to_s3"},{"filename":"/home/ubuntu/airflow_venv/lib/python3.12/site-packages/botocore/context.py","lineno":123,"name":"wrapper"},{"filename":"/home/ubuntu/airflow_venv/lib/python3.12/site-packages/boto3/s3/inject.py","lineno":175,"name":"upload_file"},{"filename":"/home/ubuntu/airflow_venv/lib/python3.12/site-packages/boto3/s3/transfer.py","lineno":378,"name":"upload_file"}]},{"exc_type":"ClientError","exc_value":"An error occurred (InvalidAccessKeyId) when calling the PutObject operation: The AWS Access Key Id you provided does not exist in our records.","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/ubuntu/airflow_venv/lib/python3.12/site-packages/boto3/s3/transfer.py","lineno":372,"name":"upload_file"},{"filename":"/home/ubuntu/airflow_venv/lib/python3.12/site-packages/s3transfer/futures.py","lineno":111,"name":"result"},{"filename":"/home/ubuntu/airflow_venv/lib/python3.12/site-packages/s3transfer/futures.py","lineno":287,"name":"result"},{"filename":"/home/ubuntu/airflow_venv/lib/python3.12/site-packages/s3transfer/tasks.py","lineno":142,"name":"__call__"},{"filename":"/home/ubuntu/airflow_venv/lib/python3.12/site-packages/s3transfer/tasks.py","lineno":165,"name":"_execute_main"},{"filename":"/home/ubuntu/airflow_venv/lib/python3.12/site-packages/s3transfer/upload.py","lineno":796,"name":"_main"},{"filename":"/home/ubuntu/airflow_venv/lib/python3.12/site-packages/botocore/client.py","lineno":595,"name":"_api_call"},{"filename":"/home/ubuntu/airflow_venv/lib/python3.12/site-packages/botocore/context.py","lineno":123,"name":"wrapper"},{"filename":"/home/ubuntu/airflow_venv/lib/python3.12/site-packages/botocore/client.py","lineno":1058,"name":"_make_api_call"}]}]}
